//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSegura.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTTipoComplejo
    {
        public int IdTipoComplejo { get; set; }
        public string DescriTipoComplejo { get; set; }
    }
}
