//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEventosDeportivosWeb.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class gestolimpEntities : DbContext
    {
        public gestolimpEntities()
            : base("name=gestolimpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TMUsuarios> TMUsuarios { get; set; }
        public virtual DbSet<TTTipoComisario> TTTipoComisario { get; set; }
        public virtual DbSet<TTTipoComplejo> TTTipoComplejo { get; set; }
    
        public virtual int TS_TMUsuarios_ActualizarToken(Nullable<int> idUsuario, string token)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var tokenParameter = token != null ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TS_TMUsuarios_ActualizarToken", idUsuarioParameter, tokenParameter);
        }
    
        public virtual ObjectResult<TS_TMUsuarios_ExisteUsuario_Result> TS_TMUsuarios_ExisteUsuario(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TS_TMUsuarios_ExisteUsuario_Result>("TS_TMUsuarios_ExisteUsuario", usuarioParameter);
        }
    }
}
