//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEventosDeportivosWeb.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTTipoComisario
    {
        public int IdTipoComisario { get; set; }
        public string DescriTipoComisario { get; set; }
    }
}
